### ISSUE TITLE
Can not build my project after i added the flutter file preview depedency. Error is Manifest merger failure.

### ISSUE THREAD

**Issue by evanswanyoike** [aliyoge/flutter_file_preview#9]
### My pubspec.yaml file

```
name: flutter_pdf_reader
description: A new Flutter pdf reader application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_file_preview:
    git:
      url: git://github.com/aliyoge/flutter_file_preview.git
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  path: ^1.6.4
  path_provider_ex: ^1.0.1
  flutter_file_manager: ^0.2.0
  get:
  ff_navigation_bar:
  syncfusion_flutter_pdfviewer: ^18.3.44-beta
  qr_code_scanner: ^0.0.13
  document_scanner: ^0.0.3
  flutter_plugin_android_lifecycle: ^1.0.11
  syncfusion_flutter_pdf: ^18.1.42-beta
  path_provider: ^1.6.5
  hive: ^1.3.0
  hive_flutter: ^0.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Open_Sans
       fonts:
         - asset: assets/fonts/OpenSans-Light.ttf
```

### The Error when trying to build

```
Launching lib\main.dart on TECNO CC6 in debug mode...
Running Gradle task 'assembleDebug'...
C:\Users\user\AndroidStudioProjects\flutter_pdf_reader\android\app\src\debug\AndroidManifest.xml:7:9-43 Error:
	Attribute application@label value=(flutter_pdf_reader) from AndroidManifest.xml:7:9-43
	is also present at [com.wuhenzhizao:titlebar:1.2.0] AndroidManifest.xml:13:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:6:4-44:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(flutter_pdf_reader) from AndroidManifest.xml:7:9-43
  	is also present at [com.wuhenzhizao:titlebar:1.2.0] AndroidManifest.xml:13:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:6:4-44:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 49s
Exception: Gradle task assembleDebug failed with exit code 1
```
